#!/bin/bash

echo "installing, please wait."

DEBIAN_FRONTEND=noninteractive sudo apt update && sudo apt install lsd -y

chmod +x {shell,langs}/*.sh

# Shell Setup
./shell/zsh.sh

# Language Setup
./langs/rust.sh

cp config/starship.toml ~/.config/starship.toml