#!/bin/bash

echo "installing, please wait."

DEBIAN_FRONTEND=noninteractive sudo apt update &&  \
    sudo apt install build-essential tmux fzf zoxide ripgrep -y

cd /tmp

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh

chmod +x rustup.sh

./rustup.sh -y
. "$HOME/.cargo/env"

cargo install --path .

cd -