[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = " "
region_aliases = {}
profile_aliases = {}
style = 'bold yellow'
expiration_symbol = 'X'
disabled = true
force_display = false

[azure]
format = '\[[$symbol($subscription)]($style)\]'
symbol = " "
style = "blue bold"
disabled = true
subscription_aliases = {  }

[battery]
charging_symbol = "󰂄 "
disabled = false
discharging_symbol = "󰂃 "
empty_symbol = "󰂎 "
format = '\[[$symbol$percentage]($style)\]'
full_symbol = "󰁹 "
unknown_symbol = "󰁽 "

[buf]
format = '\[[$symbol($version)]($style)\]'
version_format = 'v${raw}'
symbol = ""
detect_extensions = [  ]
detect_files = [ "buf.yaml", "buf.gen.yaml", "buf.work.yaml" ]
detect_folders = [  ]
style = "bold blue"
disabled = true

[bun]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = " "
detect_extensions = [  ]
detect_files = [ "bun.lockb", "bunfig.toml" ]
style = "bold red"
disabled = false

[c]
format = '\[[$symbol($name)]($style)\]'
version_format = "v${raw}"
symbol = " "
commands = [ [ "clang", "--version" ] ]
style = "149 bold"
disabled = false

[cmake]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = "󰇂 "
detect_extensions = [  ]
detect_files = [ "CMakeLists.txt", "CMakeCache.txt" ]
detect_folders = [  ]
style = "bold blue"
disabled = false

[cobol]
format = '\[[$symbol($version)]($style)\]'
symbol = " "
version_format = "v${raw}"
style = "bold blue"
detect_extensions = [ "cbl", "cob", "CBL", "COB" ]
detect_files = [  ]
detect_folders = [  ]
disabled = false

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
disabled = false
ignore_base = true
style = "green bold"
symbol = "🅒 "
truncation_length = 1

[container]
format = '\[[$symbol\[$name\]]($style)\]'
disabled = false
style = "red bold dimmed"
symbol = ""

[crystal]
format = '\[[$symbol($version)]($style)\]'
detect_extensions = [ "cr" ]
detect_files = [ "shard.yml" ]
detect_folders = [  ]
disabled = false
style = "bold red"
symbol = ""
version_format = "v${raw}"

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[ ($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[direnv]
format = '\[[$symbol$loaded/$allowed @ $rc_path]($style)\]'
symbol = " "
disabled = false

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[ ($version)( 󰩷 $tfm)]($style)\]'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln']

[elixir]
format = '\[[ ($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[ ($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[ $account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\[[ $hash$tag]($style)\]'
disabled = false
only_detached = false
tag_disabled = true

[git_state]
disabled = false
format = '\[\([$state( $progress_current/$progress_total)]($style)\)\]'
cherry_pick = '[🍒](bold red)'
bisect = '[🦬](bold yellow)'
rebase = '[](bold cyan)'
merge = '[](bold cyan)'
am = '[󰶉](bold blue)'
am_or_rebase = '[󰶉 / ](bold fg:17)'

[git_metrics]
disabled = false
format = '\[([+$added]($added_style) )([-$deleted]($deleted_style))\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol ($version)]($style)\]'
symbol = "󰟓"

[gradle]
format = '\[[$symbol ($version)]($style)\]'
symbol = ""

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[ ($version)]($style)\]'

[haxe]
format = '\[[ ($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[ ($version)]($style)\]'

[julia]
format = '\[[ ($version)]($style)\]'

[kotlin]
format = '\[[ ($version)]($style)\]'

[kubernetes]
format = '\[[󱃾 $context( \($namespace\))]($style)\]'

[lua]
format = '\[[ ($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[ ($version)]($style)\]'

[ocaml]
format = '\[[ ($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[package]
format = '\[[ $version]($style)\]'

[perl]
format = '\[[ ($version)]($style)\]'

[php]
format = '\[[ ($version)]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[ ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[ ($version)]($style)\]'

[rust]
format = '\[[ ($version)]($style)\]'

[scala]
format = '\[[ ($version)]($style)\]'

[shell]
disabled = false
format = '\[[$indicator]($style)\] '
style = 'cyan bold'
bash_indicator = "bsh"
cmd_indicator = 'cmd'
elvish_indicator = "esh"
fish_indicator = "fsh"
ion_indicator = "ion"
nu_indicator = 'nu'
powershell_indicator = 'pwsh'
pwsh_indicator = "pwsh"
tcsh_indicator = "tsh"
unknown_indicator = "?"
xonsh_indicator = "xsh"
zsh_indicator = "zsh"

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'
disabled = true # FOR THE LOVE OF YOUR LIVE, DO NOT, I REPEAT: NOT! ENABLE THE SUDO MODULE!!

[swift]
format = '\[[ ($version)]($style)\]'

[terraform]
format = '\[[󱁢 $workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'

[solidity]
format = '\[[$symbol($version)]($style)\]'